global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'springboot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['capitec-fraud-rule-engine-service:8080']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
